import type { Doctor } from "../../src/types";

export type SeedDoctor = Omit<Doctor, "autoConfirm" | "isActive" | "blockedDates" | "photoUrl">;

const standardWeek = (start = "09:00", end = "17:00", breakStart = "13:00", breakEnd = "14:00") =>
  [1, 2, 3, 4, 5].map((dayOfWeek) => ({
    dayOfWeek,
    startTime: start,
    endTime: end,
    breakStart,
    breakEnd,
    isActive: true,
  }));

export const doctors: SeedDoctor[] = [
  {
    id: "doc-1",
    name: "Dr. Amara Chen",
    specialtySlug: "dental",
    specialtyName: "General & Cosmetic Dentistry",
    experienceYears: 12,
    qualifications: ["DDS, University of California", "Fellow, Academy of Cosmetic Dentistry"],
    languages: ["English", "Mandarin"],
    bio: "Dr. Chen focuses on general and cosmetic dentistry, helping patients achieve healthy, confident smiles through evidence-based care.",
    areasOfExpertise: ["Teeth Whitening", "Crowns & Bridges", "Preventive Dentistry"],
    consultationFee: 60,
    rating: 4.9,
    reviewCount: 214,
    location: "DentiCare360 Downtown Clinic",
    supportsOnline: true,
    supportsInPerson: true,
    isTemporarilyUnavailable: false,
    availability: standardWeek("09:00", "17:00"),
    holidays: [],
  },
  {
    id: "doc-2",
    name: "Dr. Marcus Webb",
    specialtySlug: "dental",
    specialtyName: "Orthodontics",
    experienceYears: 15,
    qualifications: ["DMD, Harvard School of Dental Medicine", "Board-Certified Orthodontist"],
    languages: ["English", "Spanish"],
    bio: "Dr. Webb specializes in braces and clear aligner therapy for patients of all ages, with a gentle, detail-oriented approach.",
    areasOfExpertise: ["Braces", "Clear Aligners", "Bite Correction"],
    consultationFee: 75,
    rating: 4.8,
    reviewCount: 178,
    location: "DentiCare360 Uptown Clinic",
    supportsOnline: false,
    supportsInPerson: true,
    isTemporarilyUnavailable: false,
    availability: standardWeek("08:00", "16:00"),
    holidays: [],
  },
  {
    id: "doc-3",
    name: "Dr. Priya Nair",
    specialtySlug: "dermatology",
    specialtyName: "Dermatology",
    experienceYears: 10,
    qualifications: ["MD Dermatology, Johns Hopkins University", "American Board of Dermatology"],
    languages: ["English", "Hindi", "Tamil"],
    bio: "Dr. Nair treats acne, pigmentation, and general skin conditions with a focus on long-term skin health.",
    areasOfExpertise: ["Acne", "Pigmentation", "Skin Allergy"],
    consultationFee: 70,
    rating: 4.9,
    reviewCount: 256,
    location: "DentiCare360 Downtown Clinic",
    supportsOnline: true,
    supportsInPerson: true,
    isTemporarilyUnavailable: false,
    availability: standardWeek("10:00", "18:00"),
    holidays: [],
  },
  {
    id: "doc-4",
    name: "Dr. Julian Ferreira",
    specialtySlug: "skin-face",
    specialtyName: "Cosmetic Dermatology",
    experienceYears: 9,
    qualifications: ["MD Dermatology, University of São Paulo", "Diploma in Aesthetic Medicine"],
    languages: ["English", "Portuguese"],
    bio: "Dr. Ferreira provides anti-aging and skin health consultations, guiding patients through safe, realistic cosmetic care.",
    areasOfExpertise: ["Anti-aging", "Skin Health Consultation", "Cosmetic Guidance"],
    consultationFee: 85,
    rating: 4.7,
    reviewCount: 132,
    location: "DentiCare360 Riverside Clinic",
    supportsOnline: true,
    supportsInPerson: true,
    isTemporarilyUnavailable: true,
    unavailableReason: "On leave until next week",
    availability: standardWeek("11:00", "19:00"),
    holidays: [],
  },
  {
    id: "doc-5",
    name: "Dr. Sarah Kim",
    specialtySlug: "general",
    specialtyName: "General Medicine",
    experienceYears: 14,
    qualifications: ["MD, Stanford University School of Medicine", "Board-Certified Family Physician"],
    languages: ["English", "Korean"],
    bio: "Dr. Kim provides comprehensive primary care for everyday health concerns, preventive checkups, and chronic condition management.",
    areasOfExpertise: ["General Physician", "Preventive Health", "Women's Health"],
    consultationFee: 55,
    rating: 4.9,
    reviewCount: 301,
    location: "DentiCare360 Downtown Clinic",
    supportsOnline: true,
    supportsInPerson: true,
    isTemporarilyUnavailable: false,
    availability: standardWeek("09:00", "17:00"),
    holidays: [],
  },
  {
    id: "doc-6",
    name: "Dr. Michael Otieno",
    specialtySlug: "pediatric",
    specialtyName: "Pediatrics",
    experienceYears: 11,
    qualifications: ["MD Pediatrics, University of Nairobi", "Fellowship in Pediatric Care"],
    languages: ["English", "Swahili"],
    bio: "Dr. Otieno cares for infants, children, and teens, partnering closely with families on preventive and everyday health needs.",
    areasOfExpertise: ["Children's Health", "Pediatric Dentistry Coordination", "Vaccinations"],
    consultationFee: 50,
    rating: 4.8,
    reviewCount: 189,
    location: "DentiCare360 Uptown Clinic",
    supportsOnline: true,
    supportsInPerson: true,
    isTemporarilyUnavailable: false,
    availability: standardWeek("09:00", "16:00"),
    holidays: [],
  },
  {
    id: "doc-7",
    name: "Dr. Elena Rossi",
    specialtySlug: "dental",
    specialtyName: "Endodontics & Oral Surgery",
    experienceYears: 13,
    qualifications: ["DDS, University of Milan", "Certificate in Endodontics"],
    languages: ["English", "Italian"],
    bio: "Dr. Rossi specializes in root canal therapy, wisdom tooth extraction, and dental implants with a focus on pain-free care.",
    areasOfExpertise: ["Root Canal", "Dental Implants", "Wisdom Tooth Care"],
    consultationFee: 80,
    rating: 4.8,
    reviewCount: 165,
    location: "DentiCare360 Riverside Clinic",
    supportsOnline: false,
    supportsInPerson: true,
    isTemporarilyUnavailable: false,
    availability: standardWeek("08:30", "16:30"),
    holidays: [],
  },
  {
    id: "doc-8",
    name: "Dr. Grace Thompson",
    specialtySlug: "dermatology",
    specialtyName: "Trichology & Hair Health",
    experienceYears: 8,
    qualifications: ["MD Dermatology, University of Toronto", "Certified Trichologist"],
    languages: ["English", "French"],
    bio: "Dr. Thompson helps patients understand and manage hair loss, scalp conditions, and related skin health concerns.",
    areasOfExpertise: ["Hair Loss", "Scalp Care", "Skin Allergy"],
    consultationFee: 65,
    rating: 4.7,
    reviewCount: 98,
    location: "DentiCare360 Downtown Clinic",
    supportsOnline: true,
    supportsInPerson: true,
    isTemporarilyUnavailable: false,
    availability: standardWeek("10:00", "18:00"),
    holidays: [],
  },
];
